### ISSUE TITLE
Хранение адресов сервисов

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/ITLab-Front-Root#1]
Сейчас все фронтенды указаны в файле `src/config.json`. В дальнейшем необходимо собирать этот файл непосредственно перед сборкой single spa приложения, потому что как минимум для itlab-front файл app.js при сборке приложения будет содержать в названии хэш самого себя.

**Comment by CAPCHIK** [comment]
Можешь привести пример такой ситуации?

**Comment by IvLaptev** [comment]
При запуске команды npm run build поучается вот такой набор файлов
![Прод](https://user-images.githubusercontent.com/23360152/96960016-f557e800-1509-11eb-9cd5-3e8840b1cfb6.PNG)

Нам в конфиге надо указывать именно путь к app.js, который при сборке превращается в app.*.js

**Comment by CAPCHIK** [comment]
В конфиге разве прописывается не путь к отдельному js файлу, который проводит конфигурацию?
Или он сам в итоге запекается в общий js?

**Comment by IvLaptev** [comment]
Конфиг у меня выполняет те же функции, что и переменные среды. Я его просто импортирую и всё.
Внутри него я указываю путь к определённому ресурсу, какому-то конкретному js файлу, который уже раздаётся каким-то сервисом.

Как и здесь, один фронт поднимается на 9001 порту и без сборки основной js - app.js, а со сборкой app.*.js. Второй же фронт по умолчанию на 8500 порту, но там webpack настроен так, что при сборке название js файла не меняется, что не очень хорошо из-за кэширования страниц в браузере.
