### ISSUE TITLE
Use build tool instad scripts

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Front-Root#2]
Лучше использовать какой-то инструмент сборки, нежели два самописных скрипта build.ps1 и build.sh
Например - Jake

**Comment by IvLaptev** [comment]
Хорошо, это просто на начальном этапе как более простой вариант.

**Comment by IvLaptev** [comment]
@CAPCHIK, сейчас для билда уже везде используется Jake.js. Тем не менее в работе имеются самописные скрипты для создания побочных файлов.

Примеры ситуации, где нужен такой скрипт:
1. Во время билда ITLab-Front создаётся app.xxx.js, где xxx - хэш сбилженного файла. Чтобы прлучить такой файл надо знать его имя, поэтому скрипт создаёт файл с фиксированным именем, где хранится app.xxx.js. В этой ситуации можно конечно перенесии все команды в Jakefile, но это только увеличит время сборки, т.к. просто появляется ещё один посредник между командой и консолью.
2. Скрипт, который выносит env переменные в отдельный файл в той же ITLab-Front. Эта ситуация имеет разумное решение: немного больше углубиться в webpack и создавать файл во время билда.

Собственно вопрос: надо ли что-то менять из вышеперечисленного, или же билда при помощи Jake.js достаточно, и можно закрывать issue?

**Comment by CAPCHIK** [comment]
Кажется issue я создал когда его ещё не было, а для локальных моментов согласен, что проще сделать скрипт, так что можно закрыть
